name:
  simulink_pipeline

on:
  workflow_dispatch:

permissions:
  checks:
    write

  contents:
    read


env:
  PATH_TO_MATLAB:
    "C:\\Program Files\\MATLAB\\R2025b\\bin\\"


jobs:
  Restore_Cache:
    runs-on:
      self-hosted

    steps:
      - name:
          Checkout Repository

        uses:
          actions/checkout@v4

      - name:
          Restore Cache

        uses:
          actions/cache@v4

        with:
          key:
            padv_artifacts-${{ github.run_id }}-${{ github.run_attempt }}

          restore-keys:
            padv_artifacts-cache

          path:
            |
            Code
            derived/artifacts.dmr


      - name:
          Upload Artifacts

        if:
          ${{ !cancelled() }}

        uses:
          actions/upload-artifact@v4

        with:
          name:
            Restore_Cache_padv_artifacts

          path:
            |
            derived/artifacts.dmr
            Code

          retention-days:
            30




  Generate_Code_FC:
    if:
      ${{ !cancelled() }}

    needs:
      Restore_Cache

    runs-on:
      self-hosted

    steps:
      - name:
          Checkout Repository

        uses:
          actions/checkout@v4

      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            Restore_Cache_padv_artifacts


      - name:
          Setup MATLAB

        run:
          echo "$PATH_TO_MATLAB" >> $GITHUB_PATH

      - name:
          Launch MATLAB

        run:
          >
          & "C:\Program Files\MATLAB\R2025b\bin\matlab.exe"
          -nodesktop 
          -logfile output.log 
          -batch "openProject(pwd);runprocess(Tasks = {'padv.builtin.task.GenerateCode|sl_model_file|FC|Model/FC.slx'}, Process = 'CIPipeline', Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = false);" 

      - name:
          Upload Artifacts

        if:
          ${{ !cancelled() }}

        uses:
          actions/upload-artifact@v4

        with:
          name:
            Generate_Code_FC_padv_artifacts

          path:
            |
            derived/artifacts.dmr
            Code

          retention-days:
            30




  Generate_PADV_Report:
    if:
      ${{ !cancelled() }}

    needs:
      Generate_Code_FC

    runs-on:
      self-hosted

    steps:
      - name:
          Checkout Repository

        uses:
          actions/checkout@v4

      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            Restore_Cache_padv_artifacts


      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            Generate_Code_FC_padv_artifacts


      - name:
          Setup MATLAB

        run:
          echo "$PATH_TO_MATLAB" >> $GITHUB_PATH

      - name:
          Generate PADV Report

        run:
          >
          & "C:\Program Files\MATLAB\R2025b\bin\matlab.exe"
          -nodesktop 
          -logfile output.log 
          -batch "openProject(pwd);
          rptObj=padv.ProcessAdvisorReportGenerator(Process = 'CIPipeline', Format='pdf', OutputPath=fullfile(currentProject().RootFolder,'ProcessAdvisorReport'));
          rptObj.generateReport();" 

      - name:
          Upload Artifacts

        if:
          ${{ !cancelled() }}

        uses:
          actions/upload-artifact@v4

        with:
          name:
            Generate_PADV_Report_padv_artifacts

          path:
            |
            derived/artifacts.dmr
            ProcessAdvisorReport.pdf

          retention-days:
            30




  Collect_Artifacts:
    if:
      ${{ !cancelled() }}

    needs:
      Generate_PADV_Report

    runs-on:
      self-hosted

    steps:
      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            Restore_Cache_padv_artifacts


      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            Generate_Code_FC_padv_artifacts


      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            Generate_PADV_Report_padv_artifacts


      - name:
          Upload Artifacts

        if:
          ${{ !cancelled() }}

        uses:
          actions/upload-artifact@v4

        with:
          name:
            Collect_Artifacts_padv_artifacts

          path:
            |
            derived/artifacts.dmr
            Code

          retention-days:
            30


      - name:
          Save Cache

        uses:
          actions/cache@v4

        with:
          key:
            padv_artifacts-cache-${{ github.sha }}

          path:
            |
            Code
            derived/artifacts.dmr